### ISSUE TITLE
Feature request: set environmental variables

### ISSUE THREAD

**Issue by LasseThostrup** [mjasny/distexprunner#1]
Requesting an easy way to set environmental variables for each executed experiment.

E.g. possibility to pass another string through `run_cmd()`.

**Comment by mjasny** [comment]
Add support for environment variables: 94805a5c38bed7914e4efe89d18310549eda9a83

Usage: https://github.com/mjasny/distexprunner/blob/94805a5c38bed7914e4efe89d18310549eda9a83/experiments/example.py#L59-L67
