### ISSUE TITLE
Client doesn't terminate when experiments fails with bad return code

### ISSUE THREAD

**Issue by LasseThostrup** [mjasny/distexprunner#7]
Reproduce:
- Run experiment with a wrong executable name.
- Servers report bad rc but the progress of the client is not reflecting that the experiment failed
```python3.7 ~/distexprunner/client.py -vv --log output.log --progress runExperiment.py```

**Comment by mjasny** [comment]
![2020-07-28-194620_622x84_scrot](https://user-images.githubusercontent.com/38206637/88702223-550d4580-d10b-11ea-8d3e-1866105237d5.png)
